# gcp-terraform-project/source_code_for_pipeline/cloudbuild.yaml
steps:
# 1. Збірка Docker образу
- name: 'gcr.io/cloud-builders/docker'
  # Робоча директорія Cloud Build - це корінь репозиторію.
  # Отже, шлях до Dockerfile тепер: source_code_for_pipeline/app
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA', './source_code_for_pipeline/app']
  id: 'Build Docker Image'

# 2. Публікація Docker образу
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA']
  id: 'Push to GCR'

# 3. Розгортання в GKE
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud container clusters get-credentials "${_GKE_CLUSTER_NAME}" \
      --region "${_GKE_LOCATION}" \
      --project "$PROJECT_ID"
    
    echo "Deploying image gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA to GKE cluster ${_GKE_CLUSTER_NAME}"
    # Шлях до deployment.yaml тепер: source_code_for_pipeline/kubernetes/deployment.yaml
    sed "s|IMAGE_PLACEHOLDER|gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA|g" ./source_code_for_pipeline/kubernetes/deployment.yaml > /tmp/deployment.yaml
    cat /tmp/deployment.yaml
    kubectl apply -f /tmp/deployment.yaml
    kubectl rollout status deployment/my-simple-app --timeout=300s
  id: 'Deploy to GKE'

images:
- 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA'

substitutions:
  _IMAGE_NAME: 'my-simple-gke-app' # Це значення за замовчуванням, буде переписано з Terraform
  # _GKE_CLUSTER_NAME та _GKE_LOCATION будуть передані з Terraform