steps:
# Крок для відладки: показати структуру директорій
- name: 'gcr.io/cloud-builders/gcloud' # Можна використати 'ubuntu' або 'alpine' з entrypoint: bash
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "--- Current directory (where cloudbuild.yaml is executed from):"
    pwd
    echo "--- Listing contents of current directory:"
    ls -la
    echo "--- Listing contents of ./app (expected location of Dockerfile context):"
    ls -la ./app || echo "Directory ./app NOT FOUND"
    echo "--- Listing contents of /workspace (root of cloned repo):"
    ls -laR /workspace # Рекурсивний лістинг всього /workspace
    echo "--- Trying to find Dockerfile:"
    find /workspace -name Dockerfile

# 1. Збірка Docker образу
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA',
    '-f', 'gcp-terraform-project/source_code_for_pipeline/app/Dockerfile', # Шлях до Dockerfile від /workspace
    'gcp-terraform-project/source_code_for_pipeline/app'                  # Контекст збірки від /workspace
  ]
  id: 'Build Docker Image'


# 2. Публікація Docker образу
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA']
  id: 'Push to GCR'

# 3. Розгортання в GKE
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud container clusters get-credentials "${_GKE_CLUSTER_NAME}" \
      --region "${_GKE_LOCATION}" \
      --project "$PROJECT_ID"
    
    echo "Deploying image gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA to GKE cluster ${_GKE_CLUSTER_NAME}"
    # Шлях до deployment.yaml тепер просто './kubernetes/deployment.yaml'
    sed "s|IMAGE_PLACEHOLDER|gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA|g" ./kubernetes/deployment.yaml > /tmp/deployment.yaml # <--- ВИПРАВЛЕНО
    cat /tmp/deployment.yaml
    kubectl apply -f /tmp/deployment.yaml
    kubectl rollout status deployment/my-simple-app --timeout=300s
  id: 'Deploy to GKE'

images:
- 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA'

substitutions:
  _IMAGE_NAME: 'my-simple-gke-app'

options:
  logging: CLOUD_LOGGING_ONLY