name: CI - Build and Push to Docker Hub

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: my-app

jobs:
  build-and-push:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest 

    steps:
      # Крок 1: Клонуємо код з репозиторію
      - name: Checkout code
        uses: actions/checkout@v3

      # Крок 2: Налаштовуємо Docker Buildx 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Крок 3: Логінимось в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Крок 4: Збираємо образ і одразу завантажуємо його в Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: . 
          push: true 
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ substr(github.sha, 0, 7) }}
          cache-from: type=gha
          cache-to: type=gha,mode=max