name: CI/CD - Build, Push, and Deploy

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: my-app

jobs:
  build-and-push:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v4
        with:
          context: ./on-premise-terraform-project/source_code_for_pipeline/app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.SHORT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update Kubernetes manifest
        run: |
          MANIFEST_PATH="./on-premise-terraform-project/source_code_for_pipeline/kubernetes/deployment.yaml" 

          sed -i "s|IMAGE_PLACEHOLDER|${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.SHORT_SHA }}|g" $MANIFEST_PATH

          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions-bot@github.com"

          git add $MANIFEST_PATH
          git commit -m "CI: Update image tag to ${{ steps.vars.outputs.SHORT_SHA }}"
          git push